# -------------------------
# Primary MQTT connection
# -------------------------
listener 1883 0.0.0.0
protocol mqtt

# ----------------------------------
# Secondary WS connection for webui
# ----------------------------------
listener 9001 0.0.0.0
protocol websockets

# We don't need authentication on the rover's LAN 
# (also TLS would be too much work)
allow_anonymous true

# ---------------------
# Bridge to main broker
# ---------------------
#
# Uncomment these lines if running mosquitto
# for the arm (to bridge to the main broker on the rover)

# connection primary
# address 192.168.1.67:1883
# bridge_insecure true
# # both 0 is not a comment do not delete it, it means match all topics and 
# # bridge bidirectionally with QoS 0
# topic # both 0
